add condtion

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -48,11 +48,17 @@
             - name: run tests
               run: npm test --if-present
             
-            - name: build project
-              run: npm run build
+            - name: Build Next.js app
+              run: |
+                npm run build 2>&1 | tee build.log
+                if grep -i "warn" build.log; then
+                  echo "⚠️ Build contains warnings. Failing the pipeline."
+                  exit 1
+                fi
+
             
             - name: show all files
-              run: ls -al
+              run: ls -la .next
             
             - name: upload production build artifact
               uses: actions/upload-artifact@v4
